# Generated by Django 4.2 on 2023-04-25 00:12

import data_models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xzz_visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=60, verbose_name='Visitor Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateTimeField(verbose_name='Birthday')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('address', models.CharField(max_length=60, verbose_name='Street')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip', models.CharField(max_length=5, validators=[data_models.models.validate_zip], verbose_name='ZIP Code')),
                ('visitor_type', models.CharField(choices=[('IN', 'Individual'), ('GR', 'Group'), ('ME', 'Member'), ('ST', 'Student')], default='IN', max_length=2, verbose_name='Visitor Type')),
            ],
        ),
    ]
