# Generated by Django 4.2 on 2023-05-06 03:32

import data_models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xzz_attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction_name', models.CharField(max_length=60)),
                ('attraction_description', models.CharField(max_length=200)),
                ('attraction_type', models.CharField(choices=[('RC', 'Roller Coaster'), ('WR', 'Water Ride'), ('DR', 'Dark Ride'), ('KR', 'Kid Ride')], default='RC', max_length=2, verbose_name='Attraction Type')),
                ('attraction_status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Closed'), ('UM', 'Under Maintenance')], default='OP', max_length=2, verbose_name='Attraction Status')),
                ('capacity', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Capacity')),
                ('min_height', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Min Height')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Duration')),
                ('location', models.CharField(max_length=10, verbose_name='Location')),
            ],
            options={
                'db_table': 'xzz_attraction',
            },
        ),
        migrations.CreateModel(
            name='xzz_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='Order Date')),
            ],
            options={
                'verbose_name': 'Xzz Order',
                'verbose_name_plural': 'Xzz Orders',
                'db_table': 'xzz_order',
            },
        ),
        migrations.CreateModel(
            name='xzz_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.CharField(max_length=100)),
                ('ticket_date', models.CharField(blank=True, max_length=100)),
                ('ticket_c', models.CharField(blank=True, max_length=100)),
                ('ticket_a', models.CharField(blank=True, max_length=100)),
                ('ticket_s', models.CharField(blank=True, max_length=100)),
                ('show_select', models.CharField(blank=True, max_length=100)),
                ('show_date', models.CharField(blank=True, max_length=100)),
                ('show_c', models.CharField(blank=True, max_length=100)),
                ('show_a', models.CharField(blank=True, max_length=100)),
                ('show_s', models.CharField(blank=True, max_length=100)),
                ('store_category', models.CharField(blank=True, max_length=100)),
                ('park_place', models.CharField(blank=True, max_length=100)),
                ('park_in_date', models.CharField(blank=True, max_length=100)),
                ('park_in', models.CharField(blank=True, max_length=100)),
                ('park_out_date', models.CharField(blank=True, max_length=100)),
                ('park_out', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='xzz_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=50, verbose_name='Show Name')),
                ('show_description', models.CharField(max_length=250, verbose_name='Show Description')),
                ('show_type', models.CharField(choices=[('Drama', 'Drama'), ('Musical', 'Musical'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Adventure', 'Adventure')], default='Drama', max_length=15, verbose_name='Show Type')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('show_accessible', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, verbose_name='Wheelchair Accessible')),
                ('show_price', models.FloatField(verbose_name='Show Price')),
            ],
            options={
                'verbose_name': 'Xzz Show',
                'verbose_name_plural': 'Xzz Shows',
                'db_table': 'xzz_show',
            },
        ),
        migrations.CreateModel(
            name='xzz_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='Store Name')),
                ('category', models.CharField(choices=[('Food stall', 'Food Stall'), ('Ice cream parlor', 'Ice Cream Parlor'), ('Restaurant', 'Restaurant'), ('Gift Shop', 'Gift Shop'), ('Apparels', 'Apparels')], default='Gift Shop', max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Xzz Store',
                'verbose_name_plural': 'Xzz Stores',
                'db_table': 'xzz_store',
            },
        ),
        migrations.CreateModel(
            name='xzz_user_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='xzz_visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=60, verbose_name='Visitor Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateTimeField(verbose_name='Birthday')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('address', models.CharField(max_length=60, verbose_name='Street')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zip', models.CharField(max_length=5, validators=[data_models.validators.validate_zip], verbose_name='ZIP Code')),
                ('visitor_type', models.CharField(choices=[('IN', 'Individual'), ('GR', 'Group'), ('ME', 'Member'), ('ST', 'Student')], default='IN', max_length=2, verbose_name='Visitor Type')),
            ],
        ),
        migrations.CreateModel(
            name='xzz_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_method', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite')], default='Onsite', max_length=6, verbose_name='Ticket Method')),
                ('visit_date', models.DateTimeField(verbose_name='Visit Date')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ticket Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_order', verbose_name='Order ID')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_visitor', verbose_name='Visitor ID')),
            ],
            options={
                'verbose_name': 'Xzz Ticket',
                'verbose_name_plural': 'Xzz Tickets',
                'db_table': 'xzz_ticket',
            },
        ),
        migrations.CreateModel(
            name='xzz_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CA', 'Cash'), ('CR', 'Credit'), ('DE', 'Debit')], default='CA', max_length=15, verbose_name='Payment Method')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Payment Amount')),
                ('name_on_card', models.CharField(blank=True, max_length=30, null=True, verbose_name='Name on Card')),
                ('card_number', models.CharField(blank=True, max_length=20, null=True, validators=[data_models.validators.validate_card], verbose_name='Card Number')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('cvv', models.CharField(blank=True, max_length=3, null=True, validators=[data_models.validators.validate_cvv], verbose_name='CVV')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_order', verbose_name='Order ID')),
            ],
            options={
                'verbose_name': 'Xzz Payment',
                'verbose_name_plural': 'Xzz Payments',
                'db_table': 'xzz_payment',
            },
        ),
        migrations.CreateModel(
            name='xzz_parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=10, verbose_name='Lot')),
                ('spot', models.FloatField(verbose_name='Spot')),
                ('time_in', models.DateTimeField(verbose_name='Time In')),
                ('time_out', models.DateTimeField(blank=True, null=True, verbose_name='Time Out')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Fee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_order', verbose_name='Order ID')),
            ],
            options={
                'verbose_name': 'Xzz Parking',
                'verbose_name_plural': 'Xzz Parkings',
                'db_table': 'xzz_parking',
            },
        ),
        migrations.AddField(
            model_name='xzz_order',
            name='xzz_visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_visitor', verbose_name='Visitor ID'),
        ),
        migrations.CreateModel(
            name='xzz_orde_stor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_name', models.CharField(max_length=30, verbose_name='Menu Item Name')),
                ('menu_item_description', models.CharField(max_length=100, verbose_name='Menu Item Description')),
                ('menu_item_unit_price', models.FloatField(verbose_name='Menu Item Unit Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_order', verbose_name='Order ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_store', verbose_name='Store ID')),
            ],
            options={
                'verbose_name': 'Xzz Orde Stor',
                'verbose_name_plural': 'Xzz Orde Stors',
                'db_table': 'xzz_orde_stor',
            },
        ),
        migrations.CreateModel(
            name='xzz_orde_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_order', verbose_name='Order ID')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_show', verbose_name='Show ID')),
            ],
            options={
                'verbose_name': 'Xzz Orde Show',
                'verbose_name_plural': 'Xzz Orde Shows',
                'db_table': 'xzz_orde_show',
            },
        ),
        migrations.CreateModel(
            name='xzz_attr_visi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_in_time', models.DateTimeField(verbose_name='Time In')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_attraction', verbose_name='Attraction ID')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_visitor', verbose_name='Visitor ID')),
            ],
            options={
                'verbose_name': 'Xzz Attr Visi',
                'verbose_name_plural': 'Xzz Attr Visis',
                'db_table': 'xzz_attr_visi',
            },
        ),
    ]
