# Generated by Django 4.2 on 2023-05-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xzz_search',
            table='xzz_search',
        ),
        migrations.AlterModelTable(
            name='xzz_user_login',
            table='xzz_user_login',
        ),
        migrations.AlterModelTable(
            name='xzz_visitor',
            table='xzz_visitor',
        ),
    ]
