# Generated by Django 4.2 on 2023-05-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xzz_user_login',
            name='_is_active',
            field=models.BooleanField(db_column='is_active', default=False),
        ),
    ]
