# Generated by Django 4.2 on 2023-05-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_alter_xzz_search_table_alter_xzz_user_login_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xzz_user_login',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='xzz_visitor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
