# Generated by Django 4.2 on 2023-05-06 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_alter_xzz_user_login_email_alter_xzz_visitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='xzz_visitor',
            name='user_login',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_models.xzz_user_login'),
        ),
    ]
