# Generated by Django 4.2 on 2023-05-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0006_addmodel'),
    ]

    operations = [
    ]
