# Generated by Django 4.2 on 2023-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0009_xzz_attraction_xzz_order_xzz_show_xzz_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xzz_parking',
            name='spot',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Spot'),
        ),
    ]
